### ISSUE TITLE
Get resources configuration from Sales Configurator to fill part of the configuration in Web UI

### ISSUE THREAD

**Issue by ronanb3** [IBM/CPDemoFramework#51]
Would it be possible to use a Sales Configurator export to configure cp-deploy resources request ?
There is a CSV file with many information that could help fill in for OCP build and/or CP4D configuration.

Most of the projects use the Sales configurator for sizing so they already did a work in configuring CP4D. IT avoid redoing the work and would help the Web UI part.

**Comment by drangar** [comment]
@ronanb3 this is a good idea for production deployments for sure, however do you think we need this for demo clusters? do we even use configurator for demos etc?
